Bump minimum gtk+ version to 3.22.26
fest-im/fest pull request #18
Opened 2018-05-08 14:35 UTC by jplatte

@hellcp Is this fine with you? All other recent contributors indicated that it's fine with them (I would put a link to the relevant chat bits here, but don't know how)

2018-05-08 14:38 UTC, hellcp commented
GTK+3 seems to have stagnated on 3.22 so it's really fine, majority of platforms support it :smile:

2018-05-08 14:44 UTC, hellcp requested changes

2018-05-08 14:44 UTC, hellcp commented on src/app/launch.rs
> +                gtk::Builder::new_from_resource("/org/fest-im/fest/gtk/help-overlay.ui")
We could just use native way of showing this, with menus, as stated in comment above this line ;)

2018-05-08 14:44 UTC, hellcp commented on res/gtk/menus.ui
>    <menu id="app-menu">
This file requires just replacing `app.shortcuts` with `win.show-help-overlay`

2018-05-08 14:45 UTC, hellcp commented on res/gtk/menus.ui
>    <menu id="app-menu">
There is no point of adding keyboard shortcuts stuff to launch.rs

2018-05-08 17:00 UTC, jplatte commented
@hellcp Thanks for the fast response. Fixed.

2018-05-09 02:13 UTC, hellcp approved these changes
Perfect :D

2018-05-09 02:22 UTC, hellcp commented
We won't please Travis with anything, I will prepare Travis setup with docker and newer version of Ubuntu or some other OS later. For now: those changes look alright :D

2018-05-29 07:55 UTC, closed without merging

2018-05-29 07:57 UTC, jplatte commented
I manually rebased + pushed this to master. Travis is gone now.